import { StateModel } from './state.model';
import { AuthModel } from './auth.model';
import { Pagination } from './pagination.model';
import { Card } from './card.model';
import { AccountModel } from './account.model';
import { Transaction } from './transaction.model';
import { Ebank } from './ebank.model';
import { Transfer } from './transfer.model';
import { RoutingTable, TableRoutes } from './routin.model';
import { MerchantModel } from './merchant.model';
import { SequencesModel } from './sequences.model';
import { CodeModel } from './code.model';
import { CampaignModel } from './campaign.model';

export interface AppState {
  transactionCodes: StateModel<string[]>;
  transactionStates: StateModel<string[]>;
  transactionTypes: StateModel<string[]>;
  transactions: StateModel<Pagination<Transaction>>;
  transactionEbank: StateModel<Ebank>;
  transactionTransfers: StateModel<Transfer[]>;
  campaigns: StateModel<Pagination<CampaignModel>>;
  campaignFactories: StateModel<string[]>;
  transaction: StateModel<Transaction>;
  card: StateModel<Pagination<Card>>;
  auth: StateModel<AuthModel>;
  account: StateModel<AccountModel>;
  merchants: StateModel<Pagination<MerchantModel>>;
  issuerCodes: StateModel<CodeModel[]>;
  networkCodes: StateModel<CodeModel[]>;
  merchantCodes: StateModel<CodeModel[]>;
  orgUnitCodes: StateModel<CodeModel[]>;
  cardGroupCodes: StateModel<CodeModel[]>;
  routingTable: StateModel<RoutingTable[]>;
  routes: StateModel<TableRoutes[]>;
  rules: StateModel<string[]>;
  targets: StateModel<string[]>;
  sequences: StateModel<SequencesModel[]>;
  sequenceType: StateModel<string[]>;
  userResource: StateModel<string[]>;
  cardStates: StateModel<string[]>;
}
